### PR TITLE
Updated and reformated README.md

### PR DESCRIPTION
**Pull request by tairun**
I tried to update and reformat the README document a bit, since i was confused with the usage at first.

Also I think the Example section should be reworked. 
a) I think its a bad example because it does not show hot the base images are generated. This is confusing.  
b) It might be better to use a website which is publicly available (http://dygraphs.com/tests/dynamic-update.html) and not the admin dashboard which needs custom code to work.

### CODE REVIEW

**Comment by puneet0191** [comment]
@tairun could you please fix conflicts on this one.

**Comment by tairun** [comment]
@puneet0191  Sure thing. This should take care of it.

**Comment by puneet0191** [comment]
@tairun thanks it seems a lot of changes are getting reverted with this, could you please update your branch to latest master and then send your changes on top of it.

**Comment by puneet0191** [comment]
@tairun conflicts here again :)

**Pull request closed without merging**
